name       : ristretto
version    : 0.13.1
release    : 1
source     :
    - https://archive.xfce.org/src/apps/ristretto/0.13/ristretto-0.13.1.tar.bz2 : d71affbf15245067124725b153c908a53208c4ca1ba2d4df1ec5a1308d53791e
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : A fast and lightweight picture viewer for Xfce.
description: |
    A fast and lightweight picture viewer for Xfce.
builddeps  :
    - pkgconfig(libexif)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libxfconf-0)
    - pkgconfig(tumbler-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
